import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
const git = (...args) => execFileSync('git', args, { encoding: 'utf8', maxBuffer: 128 * 1024 * 1024 });
const files = [...new Set(git('ls-files', '--cached', '--others', '--exclude-standard').trim().split(/\r?\n/))].filter(p => fs.existsSync(p) && fs.statSync(p).isFile() && !p.startsWith('_artifacts/deep-audit-20260831/')).map(p => { const b=fs.readFileSync(p);return {path:p,bytes:b.length,lines:b.toString('utf8').split('\n').length,sha256:createHash('sha256').update(b).digest('hex')};});
const commits=git('log','--reverse','--format=%H%x09%ad%x09%s','--date=short').trim().split('\n').map(l=>{const [sha,date,...s]=l.split('\t');return {sha,date,subject:s.join('\t')};});
const churn=new Map();for(const line of git('log','--no-merges','--format=','--numstat').split('\n')){const m=line.match(/^(\d+)\t(\d+)\t(.+)$/);if(!m)continue;const v=churn.get(m[3])||{path:m[3],changes:0,added:0,removed:0};v.changes++;v.added+=Number(m[1]);v.removed+=Number(m[2]);churn.set(m[3],v);}
const months={};for(const c of commits){const k=c.date.slice(0,7);months[k]??={commits:0,dataRefresh:0};months[k].commits++;if(/^data: refresh/.test(c.subject))months[k].dataRefresh++;}
const ledgers=Object.fromEntries(['_context/BUG-POSTMORTEM.md','_context/RULES.md','_context/QA-CHECKLIST.md','CHANGELOG.md'].map(p=>{const lines=fs.readFileSync(p,'utf8').split('\n');return[p,{bytes:fs.statSync(p).size,lines:lines.length,entries:lines.flatMap((s,i)=>/^#{1,6} |^\|\s*(?:P\d|R\d)|^- \[[ x]\]/.test(s)?[{line:i+1,text:s.trim()}]:[]),openRows:p.includes('QA-')?lines.flatMap((s,i)=>/\[ \]/.test(s)?[{line:i+1,text:s.trim()}]:[]):undefined}];}));
const source=files.filter(f=>/^(src|js|worker|scripts)\/.+\.(?:m?js)$/.test(f.path)||f.path==='index.html'||f.path==='sw.js');
const texts=new Map(source.map(f=>[f.path,fs.readFileSync(f.path,'utf8')]));
const modules=source.filter(f=>f.path.startsWith('src/'));const imports=[];
for(const[file,body]of texts)for(const m of body.matchAll(/(?:\bfrom\s*|\bimport\s*\(\s*|\bimport\s*)['"]([^'"]+)['"]/g)){if(m[1].startsWith('.'))imports.push({from:file,to:path.posix.normalize(path.posix.join(path.posix.dirname(file),m[1])).split('?')[0]});}
const reachable=new Set(),todo=['src/app/bootstrap.js'];while(todo.length){const file=todo.pop();if(reachable.has(file))continue;reachable.add(file);todo.push(...imports.filter(e=>e.from===file).map(e=>e.to));}
const repeated=new Map();for(const[file,body]of texts){if(!/^(src|js)\//.test(file))continue;const lines=body.split('\n');for(let i=0;i<lines.length-11;i++){const s=lines.slice(i,i+12).join('\n').trim();if(s.length<450)continue;const h=createHash('sha256').update(s).digest('hex');const v=repeated.get(h)||{text:s,locations:[]};v.locations.push({file,line:i+1});repeated.set(h,v);}}
const duplicates=[];const ends=new Map();for(const d of repeated.values()){if(new Set(d.locations.map(l=>l.file)).size<2)continue;const first=d.locations[0];if((ends.get(first.file)||0)>=first.line)continue;duplicates.push(d);for(const l of d.locations)ends.set(l.file,l.line+11);}
const gates=files.filter(f=>/^scripts\/ci-.*\.mjs$/.test(f.path)).map(f=>{const s=texts.get(f.path)||'';return{path:f.path,bytes:f.bytes,regexChecks:(s.match(/\.includes\(|\.test\(/g)||[]).length,browser:/playwright|puppeteer|chromium/.test(s)};});
const routes=JSON.parse(fs.readFileSync('architecture/route-owners.json','utf8'));
const report={schema:'independent-code-audit-inventory.v1',generatedAt:new Date().toISOString(),version:JSON.parse(fs.readFileSync('version.json','utf8')),head:git('rev-parse','HEAD').trim(),boundary:'All available commits and current files indexed; regex reachability/duplicates are candidates, not dead-code proof. History starts at v38.9, not v1. Indexing is not per-line semantic review.',fileCount:files.length,sourceCount:source.length,files,commits,months,churn:[...churn.values()].sort((a,b)=>b.changes-a.changes),ledgers,moduleGraph:{root:'src/app/bootstrap.js',moduleCount:modules.length,reachableModuleCount:modules.filter(f=>reachable.has(f.path)).length,unreachableCandidates:modules.filter(f=>!reachable.has(f.path)).map(f=>f.path),edges:imports},duplicates,gates,routeSummary:{counts:routes.counts,routes:Object.entries(routes.routes).map(([id,r])=>({id,lifecycle:r.lifecycleOwner,renderer:r.rendererOwner,data:r.dataOwner,chart:r.chartOwner,narrative:r.narrativeOwner,loading:r.loadingStrategy}))}};
fs.writeFileSync('_artifacts/deep-audit-20260831/inventory.json',JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({files:files.length,sourceFiles:source.length,commits:commits.length,first:commits[0],months,largestSource:source.sort((a,b)=>b.bytes-a.bytes).slice(0,8),topCodeChurn:report.churn.filter(f=>/^(src|js|worker|scripts)\//.test(f.path)||f.path==='index.html').slice(0,12),moduleGraph:report.moduleGraph.unreachableCandidates,duplicateBlocks:duplicates.length,ledgers:Object.fromEntries(Object.entries(ledgers).map(([p,d])=>[p,{bytes:d.bytes,lines:d.lines,entries:d.entries.length,openRows:d.openRows?.length}]))},null,2));
